-- initial data loading

insert into filterruleclass (objectclass, objectvalue) values (0, 'Server')
insert into filterruleclass (objectclass, objectvalue) values (1, 'Logins')
insert into filterruleclass (objectclass, objectvalue) values (2, 'Endpoint')
insert into filterruleclass (objectclass, objectvalue) values (20, 'Database')
insert into filterruleclass (objectclass, objectvalue) values (21, 'Users')
insert into filterruleclass (objectclass, objectvalue) values (22, 'Roles')
insert into filterruleclass (objectclass, objectvalue) values (26, 'Assemblies')
insert into filterruleclass (objectclass, objectvalue) values (27, 'Certificates')
insert into filterruleclass (objectclass, objectvalue) values (28, 'Full-Text Catalogs')
insert into filterruleclass (objectclass, objectvalue) values (29, 'Keys')
insert into filterruleclass (objectclass, objectvalue) values (30, 'Schemas')
insert into filterruleclass (objectclass, objectvalue) values (31, 'User-Defined Data Types')
insert into filterruleclass (objectclass, objectvalue) values (32, 'XML Schema Collections')
insert into filterruleclass (objectclass, objectvalue) values (41, 'Tables')
insert into filterruleclass (objectclass, objectvalue) values (42, 'Stored Procedures')
insert into filterruleclass (objectclass, objectvalue) values (43, 'Extended Stored Procedures')
insert into filterruleclass (objectclass, objectvalue) values (44, 'Views')
insert into filterruleclass (objectclass, objectvalue) values (45, 'Functions')
insert into filterruleclass (objectclass, objectvalue) values (46, 'Synonyms')

insert into classtype (classid, classname) values (-1, 'Unknown')
insert into classtype (classid, classname) values (0, 'Database')
insert into classtype (classid, classname) values (1, 'Object or Column')
insert into classtype (classid, classname) values (3, 'Schema')
insert into classtype (classid, classname) values (4, 'Database Principal')
insert into classtype (classid, classname) values (5, 'Assembly')
insert into classtype (classid, classname) values (6, 'Type')
insert into classtype (classid, classname) values (10, 'XML Schema Collection')
insert into classtype (classid, classname) values (15, 'Message Type')
insert into classtype (classid, classname) values (16, 'Service Contract')
insert into classtype (classid, classname) values (17, 'Service')
insert into classtype (classid, classname) values (18, 'Remote Service Binding')
insert into classtype (classid, classname) values (19, 'Route')
insert into classtype (classid, classname) values (23, 'Full-Text Catalog')
insert into classtype (classid, classname) values (24, 'Symmetric Key')
insert into classtype (classid, classname) values (25, 'Certificate')
insert into classtype (classid, classname) values (26, 'Asymmetric Key')
insert into classtype (classid, classname) values (100, 'Server')
insert into classtype (classid, classname) values (101, 'Login')
insert into classtype (classid, classname) values (105, 'Endpoint')

insert into objecttype (objecttype, objecttypename) values ('AF', 'Aggregate Function (CLR)')
insert into objecttype (objecttype, objecttypename) values ('C', 'CHECK constraint')
insert into objecttype (objecttype, objecttypename) values ('D', 'DEFAULT (constraint or stand-alone)')
insert into objecttype (objecttype, objecttypename) values ('F', 'FOREIGN KEY constraint')
insert into objecttype (objecttype, objecttypename) values ('PK', 'PRIMARY KEY constraint')
insert into objecttype (objecttype, objecttypename) values ('P', 'Stored Procedure')
insert into objecttype (objecttype, objecttypename) values ('S', 'System Table')
insert into objecttype (objecttype, objecttypename) values ('PC', 'Stored Procedure (CLR)')
insert into objecttype (objecttype, objecttypename) values ('FN', 'Scalar Function')
insert into objecttype (objecttype, objecttypename) values ('FS', 'Scalar Function (CLR)')
insert into objecttype (objecttype, objecttypename) values ('FT', 'Table-valued Function (CLR)')
insert into objecttype (objecttype, objecttypename) values ('R', 'Rule (old-style, stand-alone)')
insert into objecttype (objecttype, objecttypename) values ('RF', 'Replication-filter-procedure')
insert into objecttype (objecttype, objecttypename) values ('SN', 'Synonym')
insert into objecttype (objecttype, objecttypename) values ('SQ', 'Service Queue')
insert into objecttype (objecttype, objecttypename) values ('TA', 'Assembly (CLR) DML trigger')
insert into objecttype (objecttype, objecttypename) values ('TR', 'SQL DML trigger')
insert into objecttype (objecttype, objecttypename) values ('TF', 'Table-valued Function')
insert into objecttype (objecttype, objecttypename) values ('U', 'Table')
insert into objecttype (objecttype, objecttypename) values ('UQ', 'UNIQUE constraint')
insert into objecttype (objecttype, objecttypename) values ('V', 'View')
insert into objecttype (objecttype, objecttypename) values ('X', 'Extended Stored Procedure')
insert into objecttype (objecttype, objecttypename) values ('DB', 'Database')
insert into objecttype (objecttype, objecttypename) values ('iCO', 'Column')
insert into objecttype (objecttype, objecttypename) values ('iASM', 'Assembly')
insert into objecttype (objecttype, objecttypename) values ('iCERT', 'Certificate')
insert into objecttype (objecttype, objecttypename) values ('IF', 'Inline Table-valued Function')
insert into objecttype (objecttype, objecttypename) values ('iFTXT', 'Full Text Catalog')
insert into objecttype (objecttype, objecttypename) values ('IT', 'System Table')
insert into objecttype (objecttype, objecttypename) values ('iUDT', 'User-defined Data Type')
insert into objecttype (objecttype, objecttypename) values ('iXMLS', 'XML Schema Collection')
insert into objecttype (objecttype, objecttypename) values ('iSK', 'Symmetric Key')
insert into objecttype (objecttype, objecttypename) values ('iAK', 'Asymmetric Key')
insert into objecttype (objecttype, objecttypename) values ('iSCM', 'Schema')
insert into objecttype (objecttype, objecttypename) values ('iDUSR', 'Database User')
insert into objecttype (objecttype, objecttypename) values ('iDRLE', 'Database Role')
insert into objecttype (objecttype, objecttypename) values ('iSRV', 'Server')
insert into objecttype (objecttype, objecttypename) values ('iLOGN', 'Login')
insert into objecttype (objecttype, objecttypename) values ('iENDP', 'Endpoint')


insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DB2000', 'CREATE TABLE', 'CONTROL', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DB2000', 'CREATE PROCEDURE', 'CONTROL', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DB2000', 'CREATE VIEW', 'CONTROL', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DB2000', 'CREATE DEFAULT', 'CONTROL', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DB2000', 'CREATE RULE', 'CONTROL', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DB2000', 'CREATE FUNCTION', 'CONTROL', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DB2000', 'BACKUP DATABASE', 'CONTROL', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DB2000', 'BACKUP LOG', 'CONTROL', 'SERVER', 'CONTROL SERVER')

insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'CREATE TABLE', 'ALTER', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'CREATE VIEW', 'ALTER', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'CREATE PROCEDURE', 'ALTER', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'CREATE FUNCTION', 'ALTER', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'CREATE RULE', 'ALTER', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'CREATE DEFAULT', 'ALTER', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'BACKUP DATABASE', 'CONTROL', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'BACKUP LOG', 'CONTROL', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'CREATE DATABASE', '', 'SERVER', 'CREATE ANY DATABASE')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'CREATE TYPE', 'ALTER', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'CREATE ASSEMBLY', 'ALTER ANY ASSEMBLY', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'CREATE XML SCHEMA COLLECTION', 'ALTER', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'CREATE SCHEMA', 'ALTER ANY SCHEMA', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'CREATE SYNONYM', 'ALTER', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'CREATE AGGREGATE', 'ALTER', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'CREATE ROLE', 'ALTER ANY ROLE', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'CREATE MESSAGE TYPE', 'ALTER ANY MESSAGE TYPE', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'CREATE SERVICE', 'ALTER ANY SERVICE', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'CREATE CONTRACT', 'ALTER ANY CONTRACT', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'CREATE REMOTE SERVICE BINDING', 'ALTER ANY REMOTE SERVICE BINDING', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'CREATE ROUTE', 'ALTER ANY ROUTE', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'CREATE QUEUE', 'ALTER', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'CREATE SYMMETRIC KEY', 'ALTER ANY SYMMETRIC KEY', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'CREATE ASYMMETRIC KEY', 'ALTER ANY ASYMMETRIC KEY', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'CREATE FULLTEXT CATALOG', 'ALTER ANY FULLTEXT CATALOG', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'CREATE CERTIFICATE', 'ALTER ANY CERTIFICATE', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'CREATE DATABASE DDL EVENT NOTIFICATION', 'ALTER ANY DATABASE EVENT NOTIFICATION', 'SERVER', 'CREATE DDL EVENT NOTIFICATION')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'CONNECT', 'CONNECT REPLICATION', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'CONNECT REPLICATION', 'CONTROL', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'CHECKPOINT', 'CONTROL', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'SUBSCRIBE QUERY NOTIFICATIONS', 'CONTROL', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'AUTHENTICATE', 'CONTROL', 'SERVER', 'AUTHENTICATE SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'SHOWPLAN', 'CONTROL', 'SERVER', 'ALTER TRACE')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'ALTER ANY USER', 'ALTER', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'ALTER ANY ROLE', 'ALTER', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'ALTER ANY APPLICATION ROLE', 'ALTER', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'ALTER ANY SCHEMA', 'ALTER', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'ALTER ANY ASSEMBLY', 'ALTER', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'ALTER ANY DATASPACE', 'ALTER', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'ALTER ANY MESSAGE TYPE', 'ALTER', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'ALTER ANY CONTRACT', 'ALTER', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'ALTER ANY SERVICE', 'ALTER', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'ALTER ANY REMOTE SERVICE BINDING', 'ALTER', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'ALTER ANY ROUTE', 'ALTER', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'ALTER ANY FULLTEXT CATALOG', 'ALTER', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'ALTER ANY SYMMETRIC KEY', 'ALTER', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'ALTER ANY ASYMMETRIC KEY', 'ALTER', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'ALTER ANY CERTIFICATE', 'ALTER', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'SELECT', 'CONTROL', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'INSERT', 'CONTROL', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'UPDATE', 'CONTROL', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'DELETE', 'CONTROL', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'REFERENCES', 'CONTROL', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'EXECUTE', 'CONTROL', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'ALTER ANY DATABASE DDL TRIGGER', 'ALTER', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'ALTER ANY DATABASE EVENT NOTIFICATION', 'ALTER', 'SERVER', 'ALTER ANY EVENT NOTIFICATION')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'VIEW DATABASE STATE', 'CONTROL', 'SERVER', 'VIEW SERVER STATE')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'VIEW DEFINITION', 'CONTROL', 'SERVER', 'VIEW ANY DEFINITION')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'TAKE OWNERSHIP', 'CONTROL', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'ALTER', 'CONTROL', 'SERVER', 'ALTER ANY DATABASE')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('DATABASE', 'CONTROL', '', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('OBJECT', 'SELECT', 'RECEIVE', 'SCHEMA', 'SELECT')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('OBJECT', 'UPDATE', 'CONTROL', 'SCHEMA', 'UPDATE')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('OBJECT', 'REFERENCES', 'CONTROL', 'SCHEMA', 'REFERENCES')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('OBJECT', 'INSERT', 'CONTROL', 'SCHEMA', 'INSERT')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('OBJECT', 'DELETE', 'CONTROL', 'SCHEMA', 'DELETE')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('OBJECT', 'EXECUTE', 'CONTROL', 'SCHEMA', 'EXECUTE')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('OBJECT', 'RECEIVE', 'CONTROL', 'SCHEMA', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('OBJECT', 'SELECT', 'CONTROL', 'SCHEMA', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('OBJECT', 'VIEW DEFINITION', 'CONTROL', 'SCHEMA', 'VIEW DEFINITION')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('OBJECT', 'ALTER', 'CONTROL', 'SCHEMA', 'ALTER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('OBJECT', 'TAKE OWNERSHIP', 'CONTROL', 'SCHEMA', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('OBJECT', 'CONTROL', '', 'SCHEMA', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('TYPE', 'REFERENCES', 'CONTROL', 'SCHEMA', 'REFERENCES')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('TYPE', 'EXECUTE', 'CONTROL', 'SCHEMA', 'EXECUTE')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('TYPE', 'VIEW DEFINITION', 'CONTROL', 'SCHEMA', 'VIEW DEFINITION')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('TYPE', 'TAKE OWNERSHIP', 'CONTROL', 'SCHEMA', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('TYPE', 'CONTROL', '', 'SCHEMA', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SCHEMA', 'SELECT', 'CONTROL', 'DATABASE', 'SELECT')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SCHEMA', 'INSERT', 'CONTROL', 'DATABASE', 'INSERT')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SCHEMA', 'UPDATE', 'CONTROL', 'DATABASE', 'UPDATE')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SCHEMA', 'DELETE', 'CONTROL', 'DATABASE', 'DELETE')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SCHEMA', 'REFERENCES', 'CONTROL', 'DATABASE', 'REFERENCES')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SCHEMA', 'EXECUTE', 'CONTROL', 'DATABASE', 'EXECUTE')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SCHEMA', 'VIEW DEFINITION', 'CONTROL', 'DATABASE', 'VIEW DEFINITION')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SCHEMA', 'ALTER', 'CONTROL', 'DATABASE', 'ALTER ANY SCHEMA')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SCHEMA', 'ALTER', 'CONTROL', 'DATABASE', 'ALTER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SCHEMA', 'TAKE OWNERSHIP', 'CONTROL', 'DATABASE', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SCHEMA', 'CONTROL', '', 'DATABASE', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('XML SCHEMA COLLECTION', 'REFERENCES', 'CONTROL', 'SCHEMA', 'REFERENCES')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('XML SCHEMA COLLECTION', 'EXECUTE', 'CONTROL', 'SCHEMA', 'EXECUTE')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('XML SCHEMA COLLECTION', 'VIEW DEFINITION', 'CONTROL', 'SCHEMA', 'VIEW DEFINITION')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('XML SCHEMA COLLECTION', 'ALTER', 'CONTROL', 'SCHEMA', 'ALTER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('XML SCHEMA COLLECTION', 'TAKE OWNERSHIP', 'CONTROL', 'SCHEMA', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('XML SCHEMA COLLECTION', 'CONTROL', '', 'SCHEMA', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('ASSEMBLY', 'REFERENCES', 'CONTROL', 'DATABASE', 'REFERENCES')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('ASSEMBLY', 'EXECUTE', 'CONTROL', 'DATABASE', 'EXECUTE')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('ASSEMBLY', 'VIEW DEFINITION', 'CONTROL', 'DATABASE', 'VIEW DEFINITION')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('ASSEMBLY', 'ALTER', 'CONTROL', 'DATABASE', 'ALTER ANY ASSEMBLY')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('ASSEMBLY', 'ALTER', 'CONTROL', 'DATABASE', 'ALTER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('ASSEMBLY', 'TAKE OWNERSHIP', 'CONTROL', 'DATABASE', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('ASSEMBLY', 'CONTROL', '', 'DATABASE', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('USER', 'IMPERSONATE', 'CONTROL', 'DATABASE', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('USER', 'VIEW DEFINITION', 'CONTROL', 'DATABASE', 'VIEW DEFINITION')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('USER', 'ALTER', 'CONTROL', 'DATABASE', 'ALTER ANY USER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('USER', 'ALTER', 'CONTROL', 'DATABASE', 'ALTER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('USER', 'CONTROL', '', 'DATABASE', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('ROLE', 'VIEW DEFINITION', 'CONTROL', 'DATABASE', 'VIEW DEFINITION')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('ROLE', 'ALTER', 'CONTROL', 'DATABASE', 'ALTER ANY ROLE')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('ROLE', 'ALTER', 'CONTROL', 'DATABASE', 'ALTER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('ROLE', 'TAKE OWNERSHIP', 'CONTROL', 'DATABASE', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('ROLE', 'CONTROL', '', 'DATABASE', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('APPLICATION ROLE', 'VIEW DEFINITION', 'CONTROL', 'DATABASE', 'VIEW DEFINITION')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('APPLICATION ROLE', 'ALTER', 'CONTROL', 'DATABASE', 'ALTER ANY APPLICATION ROLE')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('APPLICATION ROLE', 'ALTER', 'CONTROL', 'DATABASE', 'ALTER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('APPLICATION ROLE', 'CONTROL', '', 'DATABASE', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('MESSAGE TYPE', 'REFERENCES', 'CONTROL', 'DATABASE', 'REFERENCES')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('MESSAGE TYPE', 'VIEW DEFINITION', 'CONTROL', 'DATABASE', 'VIEW DEFINITION')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('MESSAGE TYPE', 'ALTER', 'CONTROL', 'DATABASE', 'ALTER ANY MESSAGE TYPE')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('MESSAGE TYPE', 'ALTER', 'CONTROL', 'DATABASE', 'ALTER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('MESSAGE TYPE', 'TAKE OWNERSHIP', 'CONTROL', 'DATABASE', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('MESSAGE TYPE', 'CONTROL', '', 'DATABASE', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('CONTRACT', 'REFERENCES', 'CONTROL', 'DATABASE', 'REFERENCES')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('CONTRACT', 'VIEW DEFINITION', 'CONTROL', 'DATABASE', 'VIEW DEFINITION')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('CONTRACT', 'ALTER', 'CONTROL', 'DATABASE', 'ALTER ANY CONTRACT')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('CONTRACT', 'ALTER', 'CONTROL', 'DATABASE', 'ALTER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('CONTRACT', 'TAKE OWNERSHIP', 'CONTROL', 'DATABASE', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('CONTRACT', 'CONTROL', '', 'DATABASE', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SERVICE', 'SEND', 'CONTROL', 'DATABASE', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SERVICE', 'VIEW DEFINITION', 'CONTROL', 'DATABASE', 'VIEW DEFINITION')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SERVICE', 'ALTER', 'CONTROL', 'DATABASE', 'ALTER ANY SERVICE')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SERVICE', 'TAKE OWNERSHIP', 'CONTROL', 'DATABASE', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SERVICE', 'CONTROL', '', 'DATABASE', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('REMOTE SERVICE BINDING', 'VIEW DEFINITION', 'CONTROL', 'DATABASE', 'VIEW DEFINITION')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('REMOTE SERVICE BINDING', 'ALTER', 'CONTROL', 'DATABASE', 'ALTER ANY REMOTE SERVICE BINDING')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('REMOTE SERVICE BINDING', 'ALTER', 'CONTROL', 'DATABASE', 'ALTER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('REMOTE SERVICE BINDING', 'TAKE OWNERSHIP', 'CONTROL', 'DATABASE', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('REMOTE SERVICE BINDING', 'CONTROL', '', 'DATABASE', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('ROUTE', 'VIEW DEFINITION', 'CONTROL', 'DATABASE', 'VIEW DEFINITION')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('ROUTE', 'ALTER', 'CONTROL', 'DATABASE', 'ALTER ANY ROUTE')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('ROUTE', 'ALTER', 'CONTROL', 'DATABASE', 'ALTER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('ROUTE', 'TAKE OWNERSHIP', 'CONTROL', 'DATABASE', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('ROUTE', 'CONTROL', '', 'DATABASE', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('FULLTEXT CATALOG', 'REFERENCES', 'CONTROL', 'DATABASE', 'REFERENCES')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('FULLTEXT CATALOG', 'VIEW DEFINITION', 'CONTROL', 'DATABASE', 'VIEW DEFINITION')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('FULLTEXT CATALOG', 'ALTER', 'CONTROL', 'DATABASE', 'ALTER ANY FULLTEXT CATALOG')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('FULLTEXT CATALOG', 'ALTER', 'CONTROL', 'DATABASE', 'ALTER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('FULLTEXT CATALOG', 'TAKE OWNERSHIP', 'CONTROL', 'DATABASE', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('FULLTEXT CATALOG', 'CONTROL', '', 'DATABASE', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SYMMETRIC KEY', 'REFERENCES', 'CONTROL', 'DATABASE', 'REFERENCES')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SYMMETRIC KEY', 'VIEW DEFINITION', 'CONTROL', 'DATABASE', 'VIEW DEFINITION')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SYMMETRIC KEY', 'ALTER', 'CONTROL', 'DATABASE', 'ALTER ANY SYMMETRIC KEY')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SYMMETRIC KEY', 'ALTER', 'CONTROL', 'DATABASE', 'ALTER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SYMMETRIC KEY', 'TAKE OWNERSHIP', 'CONTROL', 'DATABASE', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SYMMETRIC KEY', 'CONTROL', '', 'DATABASE', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('CERTIFICATE', 'VIEW DEFINITION', 'CONTROL', 'DATABASE', 'VIEW DEFINITION')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('CERTIFICATE', 'REFERENCES', 'CONTROL', 'DATABASE', 'REFERENCES')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('CERTIFICATE', 'ALTER', 'CONTROL', 'DATABASE', 'ALTER ANY CERTIFICATE')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('CERTIFICATE', 'ALTER', 'CONTROL', 'DATABASE', 'ALTER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('CERTIFICATE', 'TAKE OWNERSHIP', 'CONTROL', 'DATABASE', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('CERTIFICATE', 'CONTROL', '', 'DATABASE', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SERVER', 'CONNECT SQL', 'CONTROL SERVER', '', '')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SERVER', 'SHUTDOWN', 'CONTROL SERVER', '', '')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SERVER', 'CREATE ENDPOINT', 'ALTER ANY ENDPOINT', '', '')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SERVER', 'CREATE ANY DATABASE', 'ALTER ANY DATABASE', '', '')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SERVER', 'ALTER ANY LOGIN', 'CONTROL SERVER', '', '')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SERVER', 'ALTER ANY CREDENTIAL', 'CONTROL SERVER', '', '')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SERVER', 'ALTER ANY ENDPOINT', 'CONTROL SERVER', '', '')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SERVER', 'ALTER ANY LINKED SERVER', 'CONTROL SERVER', '', '')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SERVER', 'ALTER ANY CONNECTION', 'CONTROL SERVER', '', '')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SERVER', 'ALTER ANY DATABASE', 'CONTROL SERVER', '', '')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SERVER', 'ALTER RESOURCES', 'CONTROL SERVER', '', '')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SERVER', 'ALTER SETTINGS', 'CONTROL SERVER', '', '')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SERVER', 'ALTER TRACE', 'CONTROL SERVER', '', '')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SERVER', 'ADMINISTER BULK OPERATIONS', 'CONTROL SERVER', '', '')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SERVER', 'AUTHENTICATE SERVER', 'CONTROL SERVER', '', '')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SERVER', 'EXTERNAL ACCESS ASSEMBLY', 'UNSAFE ASSEMBLY', '', '')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SERVER', 'VIEW ANY DATABASE', 'VIEW ANY DEFINITION', '', '')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SERVER', 'VIEW ANY DEFINITION', 'CONTROL SERVER', '', '')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SERVER', 'VIEW SERVER STATE', 'ALTER SERVER STATE', '', '')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SERVER', 'CREATE DDL EVENT NOTIFICATION', 'ALTER ANY EVENT NOTIFICATION', '', '')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SERVER', 'CREATE TRACE EVENT NOTIFICATION', 'ALTER ANY EVENT NOTIFICATION', '', '')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SERVER', 'ALTER ANY EVENT NOTIFICATION', 'CONTROL SERVER', '', '')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SERVER', 'ALTER SERVER STATE', 'CONTROL SERVER', '', '')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SERVER', 'UNSAFE ASSEMBLY', 'CONTROL SERVER', '', '')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('SERVER', 'CONTROL SERVER', '', '', '')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('ENDPOINT', 'CONNECT', 'CONTROL', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('ENDPOINT', 'VIEW DEFINITION', 'CONTROL', 'SERVER', 'VIEW ANY DEFINITION')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('ENDPOINT', 'ALTER', 'CONTROL', 'SERVER', 'ALTER ANY ENDPOINT')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('ENDPOINT', 'TAKE OWNERSHIP', 'CONTROL', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('ENDPOINT', 'CONTROL', '', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('LOGIN', 'IMPERSONATE', 'CONTROL', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('LOGIN', 'VIEW DEFINITION', 'CONTROL', 'SERVER', 'VIEW ANY DEFINITION')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('LOGIN', 'ALTER', 'CONTROL', 'SERVER', 'ALTER ANY LOGIN')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('LOGIN', 'CONTROL', '', 'SERVER', 'CONTROL SERVER')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('ASYMMETRIC KEY', 'REFERENCES', 'CONTROL', 'DATABASE', 'REFERENCES')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('ASYMMETRIC KEY', 'VIEW DEFINITION', 'CONTROL', 'DATABASE', 'VIEW DEFINITION')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('ASYMMETRIC KEY', 'ALTER', 'CONTROL', 'DATABASE', 'ALTER ANY ASYMMETRIC KEY')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('ASYMMETRIC KEY', 'TAKE OWNERSHIP', 'CONTROL', 'DATABASE', 'CONTROL')
insert into coveringpermissionhierarchy (permissionlevel, permissionname, coveringpermissionname, parentpermissionlevel, parentcoveringpermission) values ('ASYMMETRIC KEY', 'CONTROL', '', 'DATABASE', 'CONTROL')

insert into columnpermissionreference (parentpermission, permission) values ('CONTROL', 'SELECT')
insert into columnpermissionreference (parentpermission, permission) values ('CONTROL', 'UPDATE')
insert into columnpermissionreference (parentpermission, permission) values ('CONTROL', 'REFERENCE')

insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('BULKADMIN', 'ADMINISTER BULK OPERATIONS', 'S', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DBCREATOR', 'CREATE DATABASE', 'S', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DISKADMIN', 'ALTER RESOURCES', 'S', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('PROCESSADMIN', 'ALTER ANY CONNECTION', 'S', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('PROCESSADMIN', 'ALTER SERVER STATE', 'S', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('SECURITYADMIN', 'ALTER ANY LOGIN', 'S', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('SERVERADMIN', 'ALTER ANY ENDPOINT', 'S', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('SERVERADMIN', 'ALTER RESOURCES', 'S', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('SERVERADMIN', 'ALTER SERVER STATE', 'S', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('SERVERADMIN', 'ALTER SETTINGS', 'S', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('SERVERADMIN', 'SHUTDOWN', 'S', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('SERVERADMIN', 'VIEW SERVER STATE', 'S', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('SETUPADMIN', 'ALTER ANY LINKED SERVER', 'S', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('SYSADMIN', 'CONTROL SERVER', 'S', 'N', 'Y', 'N', 'N')

insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('BULKADMIN', 'BULK INSERT', 'P', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DBCREATOR', 'ALTER DATABASE', 'P', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DBCREATOR', 'CREATE DATABASE', 'P', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DBCREATOR', 'DROP DATABASE', 'P', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DBCREATOR', 'RESTORE DATABASE', 'P', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DBCREATOR', 'RESTORE LOG', 'P', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DISKADMIN', 'DISK INIT', 'P', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('PROCESSADMIN', 'KILL', 'P', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('SECURITYADMIN', 'CREATE DATABASE', 'P', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('SERVERADMIN', 'RECONFIGURE', 'P', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('SERVERADMIN', 'SHUTDOWN', 'P', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('SETUPADMIN', 'ALTER ANY LINKED SERVER', 'P', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('SYSADMIN', 'CONTROL SERVER', 'P', 'N', 'Y', 'N', 'N')

insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_ACCESSADMIN', 'ALTER ANY USER', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_ACCESSADMIN', 'CREATE SCHEMA', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_ACCESSADMIN', 'CONNECT', 'D', 'N', 'Y', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_BACKUPOPERATOR', 'BACKUP DATABASE', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_BACKUPOPERATOR', 'BACKUP LOG', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_BACKUPOPERATOR', 'CHECKPOINT', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DATAREADER', 'SELECT', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DATAWRITER', 'DELETE', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DATAWRITER', 'INSERT', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DATAWRITER', 'UPDATE', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DDLADMIN', 'ALTER ANY ASSEMBLY', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DDLADMIN', 'ALTER ANY ASYMMETRIC KEY', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DDLADMIN', 'ALTER ANY CERTIFICATE', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DDLADMIN', 'ALTER ANY CONTRACT', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DDLADMIN', 'ALTER ANY DATABASE DDL TRIGGER', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DDLADMIN', 'ALTER ANY DATABASE EVENT', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DDLADMIN', 'NOTIFICATION', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DDLADMIN', 'ALTER ANY DATASPACE', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DDLADMIN', 'ALTER ANY FULLTEXT CATALOG', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DDLADMIN', 'ALTER ANY MESSAGE TYPE', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DDLADMIN', 'ALTER ANY REMOTE SERVICE BINDING', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DDLADMIN', 'ALTER ANY ROUTE', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DDLADMIN', 'ALTER ANY SCHEMA', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DDLADMIN', 'ALTER ANY SERVICE', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DDLADMIN', 'ALTER ANY SYMMETRIC KEY', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DDLADMIN', 'CHECKPOINT', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DDLADMIN', 'CREATE AGGREGATE', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DDLADMIN', 'CREATE DEFAULT', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DDLADMIN', 'CREATE FUNCTION', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DDLADMIN', 'CREATE PROCEDURE', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DDLADMIN', 'CREATE QUEUE', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DDLADMIN', 'CREATE RULE', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DDLADMIN', 'CREATE SYNONYM', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DDLADMIN', 'CREATE TABLE', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DDLADMIN', 'CREATE TYPE', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DDLADMIN', 'CREATE VIEW', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DDLADMIN', 'CREATE XML SCHEMA COLLECTION', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DDLADMIN', 'CREATE REFERENCES', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DENYDATAREADER', 'SELECT', 'D', 'N', 'N', 'N', 'Y')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DENYDATAWRITER', 'DELETE', 'D', 'N', 'N', 'N', 'Y')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DENYDATAWRITER', 'INSERT', 'D', 'N', 'N', 'N', 'Y')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_DENYDATAWRITER', 'UPDATE', 'D', 'N', 'N', 'N', 'Y')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_OWNER', 'CONTROL', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_SECURITYADMIN', 'ALTER ANY APPLICATION ROLE', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_SECURITYADMIN', 'ALTER ANY ROLE', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_SECURITYADMIN', 'CREATE SCHEMA', 'D', 'Y', 'N', 'N', 'N')
insert into fixedrolepermission (rolename, rolepermission, roletype, isgrant, isgrantwith, isrevoke, isdeny) values ('DB_SECURITYADMIN', 'VIEW DEFINITION', 'D', 'Y', 'N', 'N', 'N')

GRANT SELECT ON [ancillarywindowsgroup] TO [SQLSecureView]
GRANT SELECT ON [applicationactivity] TO [SQLSecureView]
GRANT SELECT ON [applicationlicense] TO [SQLSecureView]
GRANT SELECT ON [classtype] TO [SQLSecureView]
GRANT SELECT ON [collectorinfo] TO [SQLSecureView]
GRANT SELECT ON [columnpermissionreference] TO [SQLSecureView]
GRANT SELECT ON [compatibleversion] TO [SQLSecureView]
GRANT SELECT ON [coveringpermissionhierarchy] TO [SQLSecureView]
GRANT SELECT ON [currentversion] TO [SQLSecureView]
GRANT SELECT ON [databaseobject] TO [SQLSecureView]
GRANT SELECT ON [databaseobjectpermission] TO [SQLSecureView]
GRANT SELECT ON [databaseprincipal] TO [SQLSecureView]
GRANT SELECT ON [databaseprincipalpermission] TO [SQLSecureView]
GRANT SELECT ON [databaserolemember] TO [SQLSecureView]
GRANT SELECT ON [databaseschema] TO [SQLSecureView]
GRANT SELECT ON [databaseschemapermission] TO [SQLSecureView]
GRANT SELECT ON [endpoint] TO [SQLSecureView]
GRANT SELECT ON [filterrule] TO [SQLSecureView]
GRANT SELECT ON [filterruleclass] TO [SQLSecureView]
GRANT SELECT ON [filterruleheader] TO [SQLSecureView]
GRANT SELECT ON [fixedrolepermission] TO [SQLSecureView]
GRANT SELECT ON [groomingactivityhistory] TO [SQLSecureView]
GRANT SELECT ON [objecttype] TO [SQLSecureView]
GRANT SELECT ON [registeredserver] TO [SQLSecureView]
GRANT SELECT ON [serverfilterrule] TO [SQLSecureView]
GRANT SELECT ON [serverfilterruleheader] TO [SQLSecureView]
GRANT SELECT ON [serverpermission] TO [SQLSecureView]
GRANT SELECT ON [serverprincipal] TO [SQLSecureView]
GRANT SELECT ON [serverrolemember] TO [SQLSecureView]
GRANT SELECT ON [serversnapshot] TO [SQLSecureView]
GRANT SELECT ON [serverstatistic] TO [SQLSecureView]
GRANT SELECT ON [snapshothistory] TO [SQLSecureView]
GRANT SELECT ON [sqldatabase] TO [SQLSecureView]
GRANT SELECT ON [sqlserverobjecttype] TO [SQLSecureView]
GRANT SELECT ON [windowsaccount] TO [SQLSecureView]
GRANT SELECT ON [windowsgroupmember] TO [SQLSecureView]
GRANT SELECT ON [reports] TO [SQLSecureView]
GO

INSERT INTO [reports] 
	(
		[reportserver],
		[reportfolder], 
   		[reportingservicestemplate],
   		[maintemplate],
   		[reportstemplate],
   		[name1],[url1],[desc1],
   		[name2],[url2],[desc2],
   		[name3],[url3],[desc3],
   		[name4],[url4],[desc4],
   		[name5],[url5],[desc5])
 VALUES (
 		'','',
  		'http://{0}/Reports',
  		'http://{0}/Reports/Pages/Folder.aspx?ItemPath=%2f{1}',
  		'http://{0}/Reports/Pages/Report.aspx?ItemPath=%2f{1}%2f{2}',
  		'User Permissions',
              		'Security Report - User Permissions',
              		'List permissions assigned to a user.',
  		'Data Collection Filter',
              		'Control Report - Data Collection Filters',
              		'List data collection filters.',
  		'SQLsecure Users',
              		'Control Report - SQLsecure Users',
              		'List SQLsecure users.',
  		'SQLsecure Activity History',
              		'Control Report - SQLsecure Activity History',
              		'List SQLsecure activity.',
  		'Empty',
              		'Empty',
              		'Empty.'
  	)
GO

